  
name: makepkg CI

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
    branches: 
    - msys2
  #schedule:
  #  - cron: 00 15 * * *
  watch:
    types: [started]

jobs:
  build-msys2-pkg:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        install: git base-devel msys2-devel
        update: true        
    - name: CI-Build
      shell: msys2 {0}
      id: runcmd
      env:
        PACMAN_REPO: ${{secrets.PACMAN_REPO}}
        DEPLOY_PATH: ${{secrets.DEPLOY_PATH}}
        RCLONE_CONF: ${{secrets.RCLONE_CONF}}
        PGP_KEY: ${{secrets.PGP_KEY}}
        PGP_KEY_PASSWD: ${{secrets.PGP_KEY_PASSWD}}
        CUSTOM_REPOS: ${{secrets.CUSTOM_REPOS}}
      run: |
        export CI_BRANCH=$(git branch --show-current)
        export CI_COMMIT=$(git rev-parse HEAD)
        export CI_BUILD_DIR=${GITHUB_WORKSPACE}
        export CI_BUILD_NUMBER=${GITHUB_RUN_NUMBER}
        ./.github/workflows/ci-build.sh
    - name: Send mail
      uses: atomlong/send-mail-action@v2
      if: ${{ steps.runcmd.outputs.message != '' }}
      with:
        server_address: ${{secrets.MAIL_HOST}}
        server_port: ${{secrets.MAIL_PORT}}
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job of ${{github.repository}} result
        body: ${{ steps.runcmd.outputs.message }}
        to: ${{secrets.MAIL_TO}}
        from: Github
        content_type: text/html
        